.TH SKRYPT 1 18.05.2020 1.0 "SKRYPT man page"
.SH NAME
.B Portal pilkarski dla fanow ligi angielskiej! 
.SH SYNOPSIS
.PP
 ./projekt.sh - uruchomienie portalu
.PP 
 ./projekt.sh -h - uruchomienie manuala do portalu
.PP
 ./projekt.sh -v - wyswietlenie imienia, nazwiska i nr indeksu autora oraz wersji portalu
.PP
 ./projekt.sh -p - wyswietlenie wszystkich stron, z ktorych korzysta portal
.SH DESCRIPTION
.PP
Portal dostarcza najnowszych informacji dotyczacych Premier League. Uzytkownik ma do wyboru siedem opcji.
.PP
.SB Pierwsza opcja
to wyswietlenie aktualnej tabeli wraz z zaznaczeniem strefy spadkowej(kolor czerwony), strefy kwalifikujacej sie do Ligi Mistrzow(kolor ciemnozielony) i Ligi Europy(kolor jasnozielony).
.PP
.SB Druga opcja
to wyswietlenie wszystkich meczow najblizszej kolejki. Druzyna po lewej stronie jest gospodarzem.
.PP
.SB Trzecia opcja
to klasyfikacja najlepszych strzelcow TOP 10.
.PP
.SB Czwarta opcja
to najbardziej wartosciowi pod wzgledem pienieznym pilkarze TOP 10.
.PP
.SB Piata opcja
umozliwia zmiane tapety uzytkownikowi na herb swojej ulubionej druzyny. 
.PP
.SB Szosta opcja
to przeglad krotkich biografii zawodnikow z wybranych klubow. 
.PP
.SB Siodma opcja
to cytaty zawodnikow z wybranych klubow.
.SH STATUS
.I Portal caly czas sie rozwija. Dostepne opcje beda caly czas ruzbudowywane, ale takze beda wprowadzane nowe.
.SH OPTIONS
.TP
.B -h
 uruchamia manuala
.TP
.B -v
 wyświetla imie, nazwisko i nr indesku autora oraz wersje portalu
.TP
.B -p
 wyswietla wszystkie strony, z ktorych korzysta portal
.SH BUGS
.B Portal bez wad!
.SH AUTHOR
Autor: Michal Cwynar (175132)
.SH SEE ALSO
.PP
.UR https://www.onet.pl/ 
.UE
.PP
.UR https://sportowefakty.wp.pl/ 
.UE

